# Generated by Django 4.2.2 on 2023-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuickNotes", "0004_alter_note_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.TextField()),
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("password", models.TextField()),
            ],
        ),
        migrations.RenameField(model_name="note", old_name="user", new_name="email",),
    ]
