# Generated by Django 4.2.2 on 2023-08-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("QuickNotes", "0005_user_rename_user_note_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="QuickNotes.user"
            ),
        ),
    ]
