# Generated by Django 4.2.2 on 2023-08-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuickNotes", "0008_remove_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
    ]
